### ISSUE TITLE
Chaining concurrently exit code not correct?

### ISSUE THREAD

**Issue by basickarl** [open-cli-tools/concurrently#336] opened 2022-07-05 15:57 UTC
```
    "e2e:common:start": "concurrently --kill-others --success first 'yarn start:mockapi:self_serve --products aura-ds aura-db' 'npx wait-on https://localhost:9090 && yarn --cwd test/cypress e2e:self_serve:common'",
    "e2e:common": "concurrently --kill-others --success first 'yarn start:webpack:test' 'yarn e2e:common:start'",
```

```
[1] [1] npx wait-on https://localhost:9090 && yarn --cwd test/cypress e2e:self_serve:common exited with code 0
[1] --> Sending SIGTERM to other processes..
[1] [0] yarn start:mockapi:self_serve --products aura-db aura-db exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[1] yarn e2e:common:start exited with code 1
--> Sending SIGTERM to other processes..
[0] yarn start:webpack:test exited with code 1
error Command failed with exit code 1.
```

Seems to exit with code 1 even though I've set the --success correct?

Was expecting `[1] yarn e2e:common:start exited with code 1` to exit with code 0.

**Comment by gustavohenke** [comment] 2022-07-06 05:42
Hey @basickarl can you provide more information, for example OS and concurrently's version?

I got the following on my macOS + concurrently v7.2.2:

```
$ concurrently -k -s first "sleep 1 && exit 1" "sleep 0.5 && exit 0"
[1] sleep 0.5 && exit 0 exited with code 0
--> Sending SIGTERM to other processes..
[0] sleep 1 && exit 1 exited with code SIGTERM

$ echo $?
0
```

**Comment by paescuj** [comment] 2022-07-07 07:26
Duplicate of #187?

**Comment by gustavohenke** [comment] 2022-10-02 10:25
Closing for now, but please let us know if you can still replicate or if it's a duplicate of #187 🙂

**Closed by gustavohenke** 2022-10-02 10:25 UTC
Labels: pending for input
