### ISSUE TITLE
is it possible to have colors with npm wildcards command?

### ISSUE THREAD

**Issue by anisg** [open-cli-tools/concurrently#234] opened 2020-07-07 10:53 UTC
Is it possible to add colors to npm wildcards commands?

I can have colors without using wildcards, eg:
```
concurrently --names 'api,front' -c 'bgBlue.bold,bgMagenta.bold' 'echo api' 'echo front' 
```

But when I use npm wildcards there is no colors: e.g in package.json
```
"scripts": {
    "dev-api": "echo api",
    "dev-front": "echo front",
    "dev": "concurrently  -c 'bgBlue.bold,bgMagenta.bold' npm:dev-*"
  },
```

**Comment by milahu** [comment] 2021-05-08 06:45
duplicate of #210

**Closed** 2021-10-02 02:25 UTC
Labels: bug

**Comment by gustavohenke** [comment] 2021-10-02 05:29
Fix out in v6.3.0.
