### ISSUE TITLE
Options to make sure names are the same length

### ISSUE THREAD

**Issue by mastilver** [open-cli-tools/concurrently#166] opened 2018-09-22 11:45 UTC
Would you accept a PR that adds a `--min-prefix-length` options?

When using wildcards command, it's harder to make sure the name are of the same size (for aesthetic reasons)

ei.

```
[babel] Successfully compiled 26 files with Babel.
[webpack] Compiled successfully.
```

Would become (using `--min-prefix-length 7`)

```
[babel  ] Successfully compiled 26 files with Babel.
[webpack] Compiled successfully.
```

**Comment by govindrai** [comment] 2020-10-27 20:17
This would be an excellent enhancement. I have some super long service names and super short service names. Logs are super painful to traverse.

**Comment by ssukienn** [comment] 2023-01-11 17:52
This would be such a nice feature

**Comment by gustavohenke** [comment] 2023-01-14 01:03
yes @ssukienn!

**Comment by gustavohenke** [comment] 2023-10-17 01:18
Duplicate of #417

**Closed** 2024-08-16 12:56 UTC
Labels: enhancement, pull request welcome

**Comment by gustavohenke** [comment] 2024-09-08 13:12
🚢 This is now available in v9.0.0!
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
