### ISSUE TITLE
Does concurrently work with yarn2, yarn3, yarn4?

### ISSUE THREAD

**Issue by jsedanoj** [open-cli-tools/concurrently#483] opened 2024-05-31 21:53 UTC
Hello,

  I have a project that I recently migrated to yarn4. As you probably know, the differences between yarn1 and yarn2-3-4 are significant... so I was not surprised when the syntax "concurrently yarn:something:*" failed with concurrently. It says not matches found.

![image](https://github.com/open-cli-tools/concurrently/assets/12848713/0c24ccb9-5885-4b3b-9e27-9eec520cc889)

However, it works with the "non-wildcard" syntax:

![image](https://github.com/open-cli-tools/concurrently/assets/12848713/591338a0-510d-42c5-b592-0bfd65ce4ac3)

Am I correct? Does it really fail? Any chance it will fixed?

**Comment by gustavohenke** [comment] 2024-06-01 02:58
Seems like a duplicate of #292 and #309.

**Closed by gustavohenke** 2024-06-01 02:58 UTC
