### ISSUE TITLE
concurrently imports the entire date-fns library without tree-shaking but use only 1 function

### ISSUE THREAD

**Issue by guillaumeprevost** [open-cli-tools/concurrently#329] opened 2022-05-31 09:04 UTC
I have found this issue while investigating why my project still had the entire [date-fns library](https://date-fns.org/) bundled even if I was carefully importing and using only a few functions.

date-fns provides a syntax that will allow bundlers like Webpack to do some "tree-shaking" and only import the needed modules rather than the full library, optimizing greatly the total bundle size.

**It seems like concurrently doesn't use this syntax, which causes to import the full date-fns library instead of only the single function used in logging (`formatDate` in logger.ts and log-timings.ts).**

_How found this :_

I had opened [an issue about this originally on the date-fns repo](https://github.com/date-fns/date-fns/issues/3004) because I thought it came from there. 

After some discussions around the issue, someone mentioned [here](https://github.com/date-fns/date-fns/discussions/3040) that it could come from another dependency importing all of date-fns by not using tree-shaking syntax. The recommendation was to use `npm why date-fns` to spot which other dependency may use date-fns.

When running that command, it only listed my own references to date-fns (using the syntax allowing tree-shaking) and the `concurrently` library.

**Comment by gustavohenke** [comment] 2022-05-31 10:01
The two files you mention are importing a single export from date-fns:

https://github.com/open-cli-tools/concurrently/blob/74412badf0eb5402dc83fdca74843eeb305304fd/src/logger.ts#L3

https://github.com/open-cli-tools/concurrently/blob/74412badf0eb5402dc83fdca74843eeb305304fd/src/flow-control/log-timings.ts#L1

What is the problem exactly...?

**Comment by guillaumeprevost** [comment] 2022-06-08 12:54
The problem is that in the final bundle, the entire date-fns library is there , making the bundle much larger than it should be.

Indeed it seems that raised the lines should only import a single function, but that's not the case. Maybe this could work with the suggested syntax  in [their documentation ](https://date-fns.org/docs/Getting-Started) :

```
import { formatDate } from 'date-fns'
```

Or maybe the issue comes from erro in tree-shaking within the date-fns library itself ?

**Comment by gustavohenke** [comment] 2022-06-08 22:54
@guillaumeprevost can you provide a sample repo?
To begin with, I'm not sure how bundling is happening (are you building a desktop app?), so any help for me to understand which changes should be made would be great

**Comment by paescuj** [comment] 2022-07-07 07:58
```bash
tmpdir=$(mktemp -d)
pushd "$tmpdir" >/dev/null
npm install concurrently esbuild >/dev/null

echo "import concurrently from 'concurrently'; concurrently(['echo test']);" | \
npx esbuild --bundle --platform=node --analyze --outfile=/dev/null 2> >(grep date-fns)

popd >/dev/null
rm -r "$tmpdir"
```
```
   ├ node_modules/date-fns/_lib/format/formatters/index.js                           19.5kb    2.5%
   ├ node_modules/date-fns/format/index.js                                            4.8kb    0.6%
   ├ node_modules/date-fns/locale/en-US/_lib/localize/index.js                        4.0kb    0.5%
   ├ node_modules/date-fns/locale/en-US/_lib/match/index.js                           3.8kb    0.5%
   ├ node_modules/date-fns/_lib/format/longFormatters/index.js                        2.4kb    0.3%
   ├ node_modules/date-fns/locale/en-US/_lib/formatDistance/index.js                  2.4kb    0.3%
   ├ node_modules/date-fns/_lib/format/lightFormatters/index.js                       2.3kb    0.3%
   ├ node_modules/date-fns/_lib/getUTCWeekYear/index.js                               2.2kb    0.3%
   ├ node_modules/date-fns/locale/_lib/buildMatchFn/index.js                          1.8kb    0.2%
   ├ node_modules/date-fns/_lib/protectedTokens/index.js                              1.6kb    0.2%
   ├ node_modules/date-fns/_lib/startOfUTCWeekYear/index.js                           1.5kb    0.2%
   ├ node_modules/date-fns/_lib/getUTCISOWeekYear/index.js                            1.5kb    0.2%
   ├ node_modules/date-fns/_lib/startOfUTCWeek/index.js                               1.5kb    0.2%
   ├ node_modules/date-fns/locale/en-US/_lib/formatLong/index.js                      1.3kb    0.2%
   ├ node_modules/date-fns/toDate/index.js                                            1.2kb    0.2%
   ├ node_modules/date-fns/locale/_lib/buildLocalizeFn/index.js                       1.2kb    0.2%
   ├ node_modules/date-fns/locale/en-US/index.js                                      1.0kb    0.1%
   ├ node_modules/date-fns/locale/_lib/buildMatchPatternFn/index.js                   1.0kb    0.1%
   ├ node_modules/date-fns/_lib/getUTCWeek/index.js                                  1012b     0.1%
   ├ node_modules/date-fns/_lib/getUTCISOWeek/index.js                               1003b     0.1%
   ├ node_modules/date-fns/_lib/startOfUTCISOWeekYear/index.js                        993b     0.1%
   ├ node_modules/date-fns/_lib/getUTCDayOfYear/index.js                              984b     0.1%
   ├ node_modules/date-fns/_lib/startOfUTCISOWeek/index.js                            916b     0.1%
   ├ node_modules/date-fns/addMilliseconds/index.js                                   857b     0.1%
   ├ node_modules/date-fns/isValid/index.js                                           842b     0.1%
   ├ node_modules/date-fns/subMilliseconds/index.js                                   813b     0.1%
   ├ node_modules/date-fns/locale/en-US/_lib/formatRelative/index.js                  716b     0.1%
   ├ node_modules/date-fns/_lib/getTimezoneOffsetInMilliseconds/index.js              678b     0.1%
   ├ node_modules/date-fns/locale/_lib/buildFormatLongFn/index.js                     663b     0.1%
   ├ node_modules/date-fns/isDate/index.js                                            646b     0.1%
   ├ node_modules/date-fns/_lib/toInteger/index.js                                    601b     0.1%
   ├ node_modules/date-fns/_lib/addLeadingZeros/index.js                              559b     0.1%
   ├ node_modules/date-fns/_lib/requiredArgs/index.js                                 518b     0.1%
```

It seems to me that only the required files are bundled... Am I wrong?

**Comment by paescuj** [comment] 2022-07-11 21:32
Closing this as I don't see any room for improvement here on our side. Please open a new issue with a reproduction if this is still a problem.

**Closed by paescuj** 2022-07-11 21:32 UTC
Labels: pending for input

**Comment by guillaumeprevost** [comment] 2022-07-12 07:18
Hi, yes that's fair enough.. I did not have any free time to work on a minimal reproduction of this issue. 
Thank you

**Comment by jpolo** [comment] 2023-01-29 14:47
I've been investigating why node_modules is so heavy on some of my projects. Many libraries could be the cause but concurrently is on top of it. The main reason is that concurrently uses rxjs and date-fns as dependency. Those packages weight more than 10mo each. This could be problematic, especially in a CI environment...

There might be improvement from concurrently to be "lighter".

**Comment by paescuj** [comment] 2023-01-29 15:28
> I've been investigating why node_modules is so heavy on some of my projects. Many libraries could be the cause but concurrently is on top of it. The main reason is that concurrently uses rxjs and date-fns as dependency. Those packages weight more than 10mo each. This could be problematic, especially in a CI environment...
> 
> There might be improvement from concurrently to be "lighter".

Yeah, this is actually another reason why I came up with https://github.com/open-cli-tools/concurrently/pull/366 👍
