### ISSUE TITLE
Prefix-colors does not work with wildcard command.

### ISSUE THREAD

**Issue by tandat2209** [open-cli-tools/concurrently#210] opened 2019-12-25 03:28 UTC
Using `prefix-colors` with wildcard does not work.

Example : `concurrently "npm:watch-*" -c "red,green,blue" ` => Only show red

**Comment by milahu** [comment] 2021-05-08 06:47
duplicate of #186

**Closed** 2021-10-02 02:25 UTC
Labels: bug

**Comment by gustavohenke** [comment] 2021-10-02 05:28
Fix out in v6.3.0.
