### ISSUE TITLE
DeprecationWarning: The `util._extend` API is deprecated

### ISSUE THREAD

**Issue by ixxie** [open-cli-tools/concurrently#492] opened 2024-06-24 10:38 UTC
Getting a deprecation warning when running concurrently with Node 22 in Windows:
```
(node:13352) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

Environment:
```
OS: Windows 10 build 19045
Node: 22.2.0
Concurrently: 8.2.2
```

Reproduction:
```
concurrently "echo foo" "echo bar"     // warning
concurrently --help                    // no warning
```

Thank you for the awesome project!

**Comment by gustavohenke** [comment] 2024-06-24 22:41
Hey! Yeah it's been fixed, just not released yet. Duplicate of #477

**Closed by gustavohenke** 2024-06-24 22:41 UTC

**Comment by ixxie** [comment] 2024-06-25 07:20
> Hey! Yeah it's been fixed, just not released yet. Duplicate of #477

Apologies, I did a search but the error seemed different than that ticket.

Cheers!

**Comment by sathishkumar294** [comment] 2024-08-06 08:27
Hi @gustavohenke, thanks for the fix. When do you plan to release this version?

**Comment by theonlypwner** [comment] 2024-09-02 18:00
mmalecki/spawn-command#9 was fixed, so all that really needed to be done was to bump `spawn-command` to `0.0.3`.

**Comment by PatrykKuniczak** [comment] 2024-09-04 17:11
@gustavohenke Pls, realase this, because i want it very much ❤️

**Comment by gustavohenke** [comment] 2024-09-08 13:13
Hi folks, sorry for the delay, this is now fixed in v9.0.0.
https://github.com/open-cli-tools/concurrently/releases/tag/v9.0.0
