### ISSUE TITLE
Option to hide command output

### ISSUE THREAD

**Issue by kopach** [open-cli-tools/concurrently#138] opened 2018-04-10 12:38 UTC
Would be great to have an option to hide output of some process. So, e.g. by running 2 processes I only see output of one of them. I can do something like this ` &> /dev/null` but it won't work on Windows OS.

Maybe as additional feature to this, would be an ability to set log level. e.g. show only error output.

**Comment by gustavohenke** [comment] 2018-08-19 15:52
Thanks for the suggestion, @kopach!

**Comment by gustavohenke** [comment] 2018-08-20 14:46
Duplicate of #25

**Comment by akauppi** [comment] 2021-07-06 15:03
Windows itself is going way towards WSL2, and recommending it for node development.

This might open a bag of worms, but I see the reasonable footprint to support to be the Windows + WSL2 combo. If so, this would allow simplification on the side of `concurrently` code base.

**Closed** 2021-10-02 06:37 UTC
Labels: enhancement, pull request welcome

**Comment by mokone91** [comment] 2021-11-04 12:47
HI! its seems to be merged but not published yet..

**Comment by gustavohenke** [comment] 2021-11-13 01:14
Published in [`v6.4.0`](https://github.com/open-cli-tools/concurrently/releases/tag/v6.4.0)!
